const API = 'http://119.29.146.141:8882'
const APIV2 = '/api/v2'
const APIV1 = '/api/v1'

module.exports = {
  name: 'AntD Admin',
  prefix: 'antdAdmin',
  footerText: 'Ant Design Admin  © 2017 zuiidea',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: ['http://119.29.146.141:8882'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  APIV1,
  APIV2,
  api: {
    userLogin: `${APIV1}/user/login`,
    userLogout: `${APIV1}/user/logout`,
    userInfo: `${APIV1}/userInfo`,
    users: `${APIV1}/users`,
    posts: `${APIV1}/posts`,
    user: `${APIV1}/user/:id`,
    dashboard: `${APIV1}/dashboard`,
    menus: `${APIV1}/menus`,
    weather: `${APIV1}/weather`,
    v1test: `${APIV1}/test`,
    v2test: `${APIV2}/test`,
    vip:`${API}/Consumer/getConsumer`,
    vipSaveConsumer:`${API}/Consumer/saveConsumer`,
    vipDeleteConsumer:`${API}/Consumer/consumerDelete`,
    vipConsumerSearchList:`${API}/Consumer/consumerSearchList`,
    vipConsumerDetails:`${API}/Consumer/consumerDetail`,
    vipConsumerUpdateInfo:`${API}/Consumer/consumerUpdateInfo`,
    vipConsumerUpdateOk:`${API}/Consumer/consumerUpdate`,
    vipConsumerAddPet:`${API}/Consumer/consumerAddPet`,
    vipConsumerUpdatePet:`${API}/Consumer/consumerUpdatePetInfo`,
    vipConsumerupdatePetOk:`${API}/Consumer/consumerUpdatePet`,
    vipConsumerAddCard:`${API}/Consumer/consumerAddCard`,
    vipConsumerAddMetercard:`${API}/Consumer/consumerAddMetercard`,
    vipConsumerVipCardHistory:`${API}/Consumer/consumerMetercardHistory`,
    vipConsumerdeletePet:`${API}/Consumer/deletePet`,
    vipConsumerHistoryBill:`${API}/Consumer/consumerHistoryBill`,
    vipConsumerBackCardOk:`${API}/Consumer/consumerReturncard`,
    salesGetCategory:`${API}/Commodity/getCategory`,
    salesGetCommodityByCategory:`${API}/Commodity/getCommodityByCategory`,
    salesGetCommodityByOne:`${API}/Commodity/getOneCommodity`,
    salesGetCommoditySearchCustomer:`${API}/Commodity/searchCustomer`,
    salesConsumerToday:`${API}/Consumer/consumerToday`,
    salesConsumerUpdateInfo:`${API}/consumer/consumerUpdateInfo`,
    salesEmployeeList:`${API}/Commodity/employeeList`,
    salesGetConsumerPetInfo:`${API}/Consumer/getConsumerPetInfo`,
    salesMeterCardList:`${API}/Consumer/meterCardList`,
    salesSettlement:`${API}/Commodity/settlement`,
    salesRecordBill:`${API}/Commodity/recordBill`,
    SettingProductAddCategory:`${API}/Commoditygory/addCategory`,
    SettingGetOneCategory:`${API}/Commoditygory/getOneCategory`,
    SettingAddCategorytow:`${API}/Commoditygory/addCategorytow`,
    SettingGetCategory:`${API}/Commoditygory/getCategory`,
    SettingGetCommodityByCategory:`${API}/Commoditygory/getCommodityByCategory`,
    SettingDeleteCategory:`${API}/Commoditygory/deleteCategory`,
    SettingCategoryUpdateInfo:`${API}/Commoditygory/CategoryUpdateInfo`,
    SettingCategoryUpdateOk:`${API}/Commoditygory/CategoryUpdate`,
    SettingDleteleTableCommodity:`${API}/Commoditygory/deleteCommodity`,
    getCodeUrl:`${API}/Wechat/wechatJssdk`,


  },
}
